{% set name = "solar-data-tools" %}

package:
  name: "{{ name|lower }}"
  version: {{ environ.get('VERSION_FROM_GIT_TAG') }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1ad8c71d2431a892d6ba0f75471fae43b1c6154b0747785921670780e00446d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python

  run:
    - pip
    - python
    - scipy
    - numpy
    - pandas
    - scikit-learn
    - jupyter
    - matplotlib
    - seaborn
    - requests
    - pvlib
    - cvxpy
    - pykml
    - haversine
    - smart_open
    - sig-decomp
    - clarabel
    - tqdm
    - spcqe

about:
  home: https://github.com/slacgismo/solar-data-tools
  license: BSD
  license_family: BSD
  license_file:
  summary: Tools for performing common tasks on solar PV data signals
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - bmeyers
    - derins
    - thistleman
    - alejandro350
