name: Tests

on: [push]
jobs:
    run-tests:
        runs-on: ubuntu-latest
        environment: test
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

# Necessary action when needing to use AWS credentials.
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-west-1

          - name: Install Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.10'

          - name: Install Dependencies
            run: |
              sudo $pythonLocation/bin/python3 -m pip install -r requirements.txt
              sudo $pythonLocation/bin/python3 -m pip install awscli coverage
              sudo $pythonLocation/bin/python3 -m pip install setuptools --upgrade
              $pythonLocation/bin/python3 -m pip list

          - name: Run Unit Tests
            run: sudo $pythonLocation/bin/python3 -m coverage run -m unittest
